### ISSUE TITLE
Make a helper script to make a new level

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#102]
Even though making a level is pretty straightforward, there's still a good chunk that needs to be done, so it would be nice if most of that was done for us and we just filled in the blank.

Running `python make_level.py skill_name level_name` would do:
1) Make folder `skills/skill_name` if it doesn't exist
2) Add skill to `skills/__init__.py` if needed
3) Make file `skills/skill_name/__init__.py` if it doesn't exist (using template)
4) Add level to `skills/skill_name/__init__.py`
5) Make folder `skills/skill_name/_level_name`
6) Make file `skills/skill_name/_level_name/setup.spec`
7) Make file `skills/skill_name/_level_name/test.spec`
8) Make file `skills/skill_name/_level_name/instructions.txt`
9) Make file `skills/skill_name/_level_name/goal.txt`
10) Make test `skills/skill_name/test_levels.py` if it doesn't exist (using template)
11) Add test to `skills/skill_name/test_levels.py` using template

**Comment by bthayer2365** [comment]
@parkmichael777, how would you like to work on this?

**Comment by parkmichael777** [comment]
Yeah looks fun!

**Comment by parkmichael777** [comment]
For 4, do you mean add level to skills/skill_name/__init__.py?

**Comment by bthayer2365** [comment]
Yes, sorry, wrote that right before bed haha

**Comment by parkmichael777** [comment]
I setup the PR, still have to do the file addition stuff though.

**Comment by bthayer2365** [comment]
Great, don't forget to use the new data structures

**Comment by parkmichael777** [comment]
wat

**Comment by bthayer2365** [comment]
AllSkills and Skill

**Comment by parkmichael777** [comment]
Ah gotcha.
