### ISSUE TITLE
Remove git gud start/change way we initialize

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#107]
So, instead of git gud start, I think it might just make sense to load up everything we need to the first time we run git gud load. 

We can add the functionality that simply running `git gud load` will load the first level.

When handle_load runs, do the same checks that handle_start runs and return appropriate output for the new situation.

**Comment by bthayer2365** [comment]
@wertydoo Do you want to work on this?

**Comment by benthayer** [comment]
I will be working on this

**Comment by benthayer** [comment]
Done.
