### ISSUE TITLE
Commands to add/remove git gud alias

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#108]
`git gud register` should emulate `git config alias.gud "! /path/to/python -m gitgud"`

It should also be able to handle the --local and --global config levels, with global being the default.

`git gud unregister` should emulate `git config --unset-all alias.gud` and should also be able to handle config level options. In this situation, the default should be to unregister from --local if it exists in the repo, and --global if it's not registered locally.

**Comment by bthayer2365** [comment]
@wertydoo Do you want to work on this?
