### ISSUE TITLE
When running git gud outside of a directory, give instructions for starting the game

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#116]
People download git gud and don't know what to do, so running git gud should tell them to make a directory and run `git gud init` inside that directory

**Comment by benthayer** [comment]
@sahansk2 I think the current help page gives a decent description of what to do, but I think if someone's a beginner, they're not going to neccessarily know how to navigate that help page. 

Do you think we could add `Get started by running "git gud init" in a new directory.` somewhere in the main help page?

**Comment by sahansk2** [comment]
@benthayer When you say the "main help page", do you mean the output of running `git gud` by its own? I feel like that might end up being cluttered, especially if it's going to appear every single time `git gud` is run by its own.

Would it be better to maybe output `Get started by running "git gud init" in a new directory.` immediately after the user installs the program (i.e. immediately after running `pip3 install git-gud`)?

**Comment by benthayer** [comment]
So I'm thinking we get rid of the current output of `git gud` (the
equivalent of `git gud help`) and turn it into something like what you
said. I think outputting it after the install wouldn't make as much sense,
especially if someone forgets about it and then needs to figure it out
later. We can also have the output of `git gud` depend on whether it's in
an inited directly. If it is, we can do the normal output
