### ISSUE TITLE
Add Flake8 test

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#121]
We should test to make sure the changes comply with [pep8](https://www.python.org/dev/peps/pep-0008/)

[Flake8](https://pypi.org/project/flake8/) is a useful tool

The test should go into the `.circleci/config.yml`, and a PR should involve fixing issues with pep8 such that the tests pass.

**Comment by benthayer** [comment]
@karywjh Would you be interested in doing this? PEP8 is a Python standard for formatting code. It's not strict, but it makes things easier to read. Flake8 tests to make sure all the files/spacing/variable names etc follow that format, and CircleCI is for continuous deployment and running those tests automatically.

**Comment by sahansk2** [comment]
I'll be looking at this now.
