### ISSUE TITLE
Warn user when force initializing git gud

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#122]
We probably shouldn't be deleting people's files, so it'd be a good idea to create a commit that saves them and then just dereference that commit. We can let git save the commit object, but we could also create our own copy of the backup in the `.git/gud/backups` folder or something. We can find the commit hash using `git gud backups` and restore using `git checkout <hash>`

**Comment by benthayer** [comment]
@sahansk2 What are your thoughts on this? Maybe we should just add a line that says 

```FORCE INITIALIZING WILL DELETE ALL YOUR FILES
FORCE INITIALIZING WILL DELETE ALL YOUR FILES
FORCE INITIALIZING WILL DELETE ALL YOUR FILES
FORCE INITIALIZING WILL DELETE ALL YOUR FILES

**Comment by sahansk2** [comment]
Ha! That message is glorious. We could honestly do something fun there, like
```
FORCE INITIALIZING WILL DELETE ALL YOUR FILES. Abandon hope, ye who `git gud init --force`.
If you really want to force initialize, run `git gud init --force --prettyplease`.
```
or maybe, we have some kind of `input()` confirmation:
```
FORCE INITIALIZING WILL DELETE ALL YOUR FILES. Seriously.
Continue? [y/N]
```
About preventing git gud from force initializing at all: I don't know if that's such a good idea. It's possible that the user does `git gud init --force` in order to update their version of gitgud (maybe because their current version breaks with API changes or something because of how data is stored). If that's the case, then the user might just delete everything by themselves, and then run `git gud init`. I've had that kind of a situation before: I had to do `git gud init --force` to installations because they was too old for git gud to interact with (weird errors were popping up).

**Comment by benthayer** [comment]
I've done the same thing. It's habit to run `--force` every time because there are frequently changes that break things.

Here's what I'm thinking:

Behavior:
 - `git gud init` runs normally if it's an empty directory
 - `git gud init --force` runs normally if the `.git/gud` directory exists
 - `git gud init --force --prettyplease` will delete everything then re-initialize

Logging:
 - If `git gud init` fails, inform the user that running `git gud init --force` will delete their progress
 - If `git gud init --force` fails, inform the user that running `git gud init --force --prettyplease` will delete all of their files
 - If `git gud init --force` fails, tell the user the current directory
 - If `git gud init --force` fails, tell the user how many files they have

**Comment by benthayer** [comment]
So @sahansk2, can you implement all of that and put in whatever fun logging you want

**Comment by sahansk2** [comment]
Sure, sounds good!

**Comment by sahansk2** [comment]
> If git gud init fails in a directory where git gud has been initialized, inform the user that running git gud init --force will delete their progress

By necessity, #32 will have to be completed first.

**Comment by benthayer** [comment]
The work can be done asynchronously. It's just the user message that is affected.

**Comment by sahansk2** [comment]
Well, I've had my first problem where resolution of this issue would've prevented the problem.

I'm so used to running `git gud init --force` that I ran it in the `git-gud` project repository, and not in the `test` directory...and I lost my local commits.

It was only two commits, but still...:sob:

**Comment by benthayer** [comment]
All the best things happen at 3am. Are you working on this or do you want me to take over? I can make this my next focus

**Comment by sahansk2** [comment]
I wasn't working on this at the present moment, so you could take over @benthayer

**Comment by benthayer** [comment]
https://github.com/benthayer/git-gud/pull/270#issuecomment-670959649
