### ISSUE TITLE
Git hooks (.git/hooks) shellscripts do not have executable permission

### ISSUE THREAD

**Issue by parkmichael777** [benthayer/git-gud#125]
Performing a successful rebase does not trigger the post-rewrite hook. Running the hook manually (.git/hooks/<hook_name> in testing directory) gives a permission denied error. Run "chmod +x <hook_name>" to get executable permission. The hook will now run with a successful rebase. 

Need to fix executable permission on these files to make sure users do not have to do this.

See #77 for more details

**Comment by sahansk2** [comment]
Looks pretty similar to #77 , take a look if you'd like.

**Comment by parkmichael777** [comment]
> I believe this is a duplicate of #77.

**Comment by parkmichael777** [comment]
@sahansk2 Did you fix this? I discovered this error while testing a new feature so Ben told me to open it as a new issue.

**Comment by sahansk2** [comment]
@divCurlF made a fix for it, but it still had some small changes to be made. Since the PR was inactive for a while, I just put divCurlF's code into #128 and put the fixes in -- there are still merge conflicts, though.

**Comment by parkmichael777** [comment]
@sahansk2 Ah gotcha, I'm working off the latest version of Ben's master so I thought it was still broken. But you're saying it hasn't been pulled by Ben yet right?

**Comment by sahansk2** [comment]
Pretty sure it's still broken in master at this time: the only PRs that have a fix are #79 and #128, neither of which have been merged into master.

**Comment by parkmichael777** [comment]
@sahansk2 oke doke, thanks!

**Comment by benthayer** [comment]
Sorry guys, I knew this was an issue before but thought it had already been fixed and was a different issue. I guess #79's name was confusing me.
