### ISSUE TITLE
Ignore capitalization for user-created branch names

### ISSUE THREAD

**Issue by sahansk2** [benthayer/git-gud#139]
When running `git gud test`, the capitalization of the branch names should be disregarded. For example, if on the `basics-branching` level, the user is prompted to create the branch `bugFix` in one of the steps. If the user creates the branch `BugFix` instead of `bugFix` but does all the other necessary steps correctly, we should accept the solution and deem it solved, instead of rejecting it outright.

**Comment by benthayer** [comment]
Just noting that I think we should have a log message telling people to remember that git is case sensitive if they get the capitalization "wrong"

**Comment by benthayer** [comment]
@sahansk2 can you work on this again

**Comment by sahansk2** [comment]
I'll be tackling this again.
