### ISSUE TITLE
Test user-facing commands for errors

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#171]
We currently do nothing to test that the commands the user sees don't have issues.

If we have a bad reference to a variable in a method that is only called by users, we may have an undefined variable that isn't covered in the test cases. We should make sure that users will never see things like `NameError: name 'passed_path' is not defined`

**Comment by benthayer** [comment]
Closing in favor of #197

**Comment by sahansk2** [comment]
@benthayer Hoop
