### ISSUE TITLE
Develop a framework to automatically generate the gif preview in the README

### ISSUE THREAD

**Issue by sahansk2** [benthayer/git-gud#189]
This is related to #138 .
We should not need to open issues to fix the same thing: updating the GIF preview in the README. If we need to update that preview, we should have some sort of a framework which can (1) effectively record the demo commands in the asciinema session by itself, and (2) automatically converts the asciinema output recording into a GIF file, such that if we ever need to update the gif preview, we can just push to the file which contains all of the updated commands.

**Comment by benthayer** [comment]
We should also test if the code asciinema is running works as expected. Maybe we'll need to autogenerate it?

**Comment by sahansk2** [comment]
I think that it's best to use [demo-magic.sh](https://github.com/paxtonhare/demo-magic) along with asciinema for this. demo-magic.sh for the automated typing, and asciinema for the recording.

**Comment by benthayer** [comment]
Okay, cool. Feel free to get started
