### ISSUE TITLE
Refactor file operator code and complete git init level

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#202]
level `intro/init` is used to teach someone to use `git init`, but for them to do that, the current directory should not be a git repo. In order to do that,we would need to add several layers of convolution to get the file operators but instead, let's just refactor

Task:
 - Remove ownership of file operators from the GitGud object
 - Never pass file operators, instead get it from `operations.get_operator()`  (Never re-initialize)
 - Make sure `git init` acts as if we aren't in a git repo when the level is initialized and the shows up as it would normally after running `git init`
 - Refactor existing code that uses file operators to reflect changes
 - Fix anything else that's relevant to this and you think makes sense. You're at liberty to change the structure of the code here if you think it'd help

Base changes on and merge into https://github.com/benthayer/git-gud/tree/intro

**Comment by benthayer** [comment]
@sahansk2 Can you tackle this?

**Comment by sahansk2** [comment]
@benthayer Yep!
