### ISSUE TITLE
Generate solution for rampup/detaching

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#215]
Once we merge #187, we will need to generate a user-friendly solution to rampup/detaching.

Current solution:
```
git checkout bugFix
git checkout @^
git checkout @{1}
```
Ideal solution:
```
git checkout <commithash>
```
To find the commit hash, we will need to override the `Level.solution()` method

**Comment by sahansk2** [comment]
I'll try to tackle this issue after #236 is merged.

**Comment by benthayer** [comment]
@sahansk2 #236 has been merged, are you ready to give this a go?

**Comment by sahansk2** [comment]
Does #268 make this issue irrelevant?

**Comment by benthayer** [comment]
Yes
