### ISSUE TITLE
Don't confirm `git gud solution` if level has ever been completed

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#216]
Once #32 and #187 are done, we should allow users to run `git gud solution` without needing to confirm if they have already completed the level at any point. Code would go in  `Level.has_ever_been_completed()`

**Comment by benthayer** [comment]
@sahansk2 This one is going to you because you're implementing all the related stuff. Can you comment here so I can assign it to you?

**Comment by sahansk2** [comment]
@benthayer Scoop
