### ISSUE TITLE
Remove `parse_name` from `operations.py`

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#219]
We have a new system for handling reverts that uses diffs rather than this method, which relies on the name of the commit

**Comment by sahansk2** [comment]
Is this related to #224 ?

**Comment by benthayer** [comment]
Yes, this is a prerequisite.

**Comment by benthayer** [comment]
Fixed in 4b2bd04eab163a1a7625b7a817f3b1673fe74ae5
