### ISSUE TITLE
Level: Basics 1 - "First Commit"

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#246]
```
1) First Commit - Show that you can add/commit - Commits contain files (adapt from basics-committing)
```
Just add a file and commit that file.

Status shows your progress in a way somewhat like this.
```
 Created: Yes
 Added: No
 Committed: No
```

The level demonstrates the process and shows how files must be added before they are considered part of a commit

**Comment by sahansk2** [comment]
@benthayer Woop
