### ISSUE TITLE
Level: Basics 2 - "Two Commits"

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#247]
```
2) Two Commits - Commits are sequential - Branch updates as you commit
```
In this level, commits are shown to follow one another, so when you make a new commit, the old commit is still there. It also makes the differentiation between the working directory and the staging area, making the point that each of them as well as each commit is associated with a state of the directory.

Solution:
touch file1
git add file1
git commit
touch file2
git add file2
git commit

`git gud status`
```
Working Directory:
 File 1: Exists
 File 2: Exists
Staging Area:
 File 1: Exists
 File 2: Exists
Commit 1: Doesn't exist
Commit 2: Doesn't exist
```
Once things start getting committed, we can change to a view like this
```
"Initial commit":
 File 1: Exists
 File 2: Doesn't exist
"Hello world commit" (master):
 File 1: Exists
 File 2: Exists
```

Similarly, we can name File 1 and File 2 to according to their actual name, just like we did with commit messages

**Comment by sahansk2** [comment]
@benthayer Shoop
