### ISSUE TITLE
Allow loading by level/challenge numbers

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#26]
Right now, we just load challenges by their names, but it might be useful to load them by their challenge numbers in addition to by name.

This issue can't be fixed until #23 is complete.

**Comment by bthayer2365** [comment]
@sahansk2 Would you also like to handle this?

**Comment by bthayer2365** [comment]
You'll need to make sure to show the numbers when running `git gud skills`

**Comment by sahansk2** [comment]
Sure, I'll take on this issue. I'll open a pull request for it as well.
