### ISSUE TITLE
Status Method for Basics 2-8

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#267]
All basic levels in #238 (bar one) use the same or similar status messages to communicate information about commits in the level.

 - #247
 - #248
 - #253
 - #249
 - #261
 - #250
 - #251

The status method should be worked on before any of the levels so all levels can use it.

Can configure
 - Show "Exists" vs Content
 - Show branch
 - Show working directory and staging area or not
 - Potentially more
```
"Initial commit":
 sahan.txt: Exists
 File 2: Doesn't exist
```
```
"Hello world commit" (master):
 sahan.txt: "Hola mundo"
 ben.txt: "Wiggle my toes"
```

**Comment by sahansk2** [comment]
@benthayer Bidoof
