### ISSUE TITLE
Update Operator to get contents of commit files

### ISSUE THREAD

**Issue by sahansk2** [benthayer/git-gud#288]
We'd like to have a common method to get the contents of a file in a commit, something like
```
def commit_content(self, commit, filepath)
```
since this is pretty crucial for level development in #238.

`commit` could support taking a [Commit](https://gitpython.readthedocs.io/en/stable/tutorial.html#the-commit-object) object, or a string commit-ish.

`filepath` should support taking [Path](https://docs.python.org/3/library/pathlib.html) objects and string representations of paths.

**Comment by benthayer** [comment]
This is pretty similar to the implementation of #286 .

We should also be wary of reading the data stream, which can only be read from once.
