### ISSUE TITLE
Remove `git gud progress` and replace with `git gud load next`

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#31]
People read progress as if it is the noun, when I originally meant it to be the verb. That is confusing, so I think it would be good to make loading the next level a special case of the `load` subcommand.

We'll also need to make sure we change the instructions to match this change, so nobody types in `git gud progress` expecting to load the next level

Relevant methods are `handle_progress` and `handle_load` in `gitgud/__main__.py`

**Comment by TSSlade** [comment]
I'd like to try to take this on.
