### ISSUE TITLE
Track which levels have been completed

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#32]
Since users can complete challenges out of order, it might be fun to save which challenges have been beaten. It would probably make the most sense to store this information in a json file in the `.git/gud` directory that is created after we run `git gud start`. It might be good to name it `progress.json` and store three values so we know whether a level has been attempted yet

The structure of the json in `progress.json` would be like this
```
{
'intro commits': 'complete',
'intro branching': 'incomplete',
'intro merging': 'unviewed',
...
} 
```

We may want to add more later on, but this is a good start and will allow us to just use the full names of the challenges when determining whether they're complete.

When loading levels, we can output something like "This level has already been complete" or "This level has not yet been completed", probably something more fun.

If someone wants to check their level progress, they can type in `git gud progress` or it might make sense to show the progress when using `git gud levels`. I'll let whoever works on this issue decide what to do there.
If we use `git gud progress`, we'll need to wait for #31 to be complete since we're going to be using the same command.

We will also have to be conscious of new levels being added, so if a key is not in that file, we should add it. 

Relevant method is `handle_progress` in `gitgud/__main__.py`

**Comment by benthayer** [comment]
@wertydoo Do you want to tackle this?

**Comment by benthayer** [comment]
@sahansk2 Can you comment here so I can assign the issue to you

**Comment by sahansk2** [comment]
@benthayer Zoop :sunglasses:
