### ISSUE TITLE
git gud show-tree not found.

### ISSUE THREAD

**Issue by saivishnu725** [benthayer/git-gud#341]
I've completed some levels (upto Detach HEAD) and some levels said me to use ```git gud show-tree``` command
![image](https://user-images.githubusercontent.com/39369597/114432073-e828d580-9bdd-11eb-932b-fc081823eb0e.png) but running the command shows this help message 
![image](https://user-images.githubusercontent.com/39369597/114432127-f840b500-9bdd-11eb-9cdc-23e08d68138c.png). Am I doing it wrong or is that a issue?

**Comment by sahansk2** [comment]
This is fixed in #20, but it isn't in the current release yet. `git gud show tree` should work, so just run that instead of `git gud show-tree`.

**Comment by benthayer** [comment]
This should be fixed in v0.4.1 which I just released
