### ISSUE TITLE
Disable committing in favor of using git gud commit using git hooks

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#39]
When users are using git gud, we want more control over what they're committing so that we can track their progress, so we should disable the git commit command. We can do this using the pre-commit git hook and exiting with a non-zero value. It can be anything, but let's use 1.

We'll also want a log message that tells the user what happend, so we can make a simple file that prints out a log message, then calls `exit(1)`

See `gitgud/hooks/` for examples

This is also useful reference, but you shouldn't need it here: https://git-scm.com/docs/githooks

**Comment by divCurlF** [comment]
I'll be working on this
