### ISSUE TITLE
Complete the `post-rewrite` hook to keep track which commits have been rebased

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#43]
We'll need to put this information in the json file created by #40. When a commit is rebased, we'll want to remember the hash of the previous commit, and we'll want to remember the new commit so we can check if the commit was actually rebased. Once this is implemented, we'll want to update the levels that involve rebasing to take advantage of the newly defined git hook.

Learn Git Branching represents rebased commits with an apostrophe, such that after a rebase, `1` would become `1'`. It's interesting to note that the command line doesn't get rid of the single quote while the double-quote is treated like a special character and isn't allowed to be used in a commit name.

If rebasing a rebased commit, add another `'`, so `1'` rebased is `1''`

**Comment by bthayer2365** [comment]
@jakeduo, would you like to work on this?

**Comment by JakeDuo** [comment]
Sure, I'll ask you if I need any help figuring things out.

**Comment by benthayer** [comment]
With the addition of #104, we'll need to make sure we add the rebase notation to the spec file templates

**Comment by benthayer** [comment]
@JakeDuo How's this coming? You can work with @parkmichael777 on this and #87. If either of you need help, let me know

**Comment by benthayer** [comment]
@JakeDuo 

I'm trying to get Git Gud into beta by the beginning of break so I can start talking to people and seeing how they interact with it and then add some more final features over break and hopefully start getting professors to use it in their classes next semester. Can you get together within the next week or so, so I can help you get started on this?

**Comment by parkmichael777** [comment]
@benthayer @JakeDuo This is next on the todo list. I can do it in a couple lines using the stuff already there and the json tracking code I wrote. Can I take this issue?

**Comment by JakeDuo** [comment]
Sure

**Comment by JakeDuo** [comment]
@parkmichael777 Sure

**Comment by parkmichael777** [comment]
Fixed by #132
