### ISSUE TITLE
Add full names to levels

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#49]
It would be nice to display full, stylized names like "Getting started" instead of "intro committing". You'll need to add a parameter to the Challenge class, call it something like `self.human_name`. Then, go through the existing challenge and add fun/creative names to each of the levels and then output the human name of the challenge when loading it.

**Comment by bthayer2365** [comment]
@TSSlade, are you planning on doing this? A lot has changed, so you'll need to make sure to start your work from ben/master. You can leave `full_name()` as is and just change the constructor to be `__init__(self, name, human_name)` and include human_name as a parameter to be accessed. You'll need to go back and change the usages of `full_name()` to `human_name` except when writing to the level file

**Comment by benthayer** [comment]
@karywjh Does this look interesting to you?
