### ISSUE TITLE
Add support for git remotes

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#51]
For now, this is just meant to be a note. When someone starts working on a level that requires remotes, we can talk about it here.

Eventually, we're going to need to have levels that support using remote repositories so users can practice clone/fetch/push/pull etc. We'll probably need a set of commands to go along with this and simulate actions on the remote repository, just like Learn Git Branching does. It would also be cool if we could add support for multiple repositories to simulate things like merge conflicts and whatnot

Ideally, we also make the remote name look clean so users can do something like `git remote add origin gitgud:user1/repo.git` or something. Maybe we can use file descriptors or symbolic links for that.  Later on, we might want to do some funky stuff like practicing interactions with GitHub. Once this issues is closed, we can open up another one that starts thinking about how to do these other things.

**Comment by bthayer2365** [comment]
Most likely #80 will need to be solved for levels including remotes to work properly

**Comment by benthayer** [comment]
This will be handled as a side effect of any new levels that require using remotes.
I don't think we should work on it until we have a level to guide the implementation, so I'm closing
