### ISSUE TITLE
Add Challenges from learngitbranching.js.org

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#52]
[Learn Git Branching](learngitbranching.js.org) is a great resource that we're trying to emulate and extend. To get Git Gud up and running, our first step is to copy all of their levels, and then we can start thinking about more interesting situations and build up a repository of tougher and more in depth git challenges and guides to practice on.

To be clear about our place relative to Learn Git Branching: I absolutely love it, and think it is great for visualizing everything that's happening, especially if you're new to Git. I would not have learned Git as well without it. When I was first learning Git, it really helped clarify exactly what was happening, and I didn't feel like I truly understood what was going on until I used Learn Git Branching. I created Git Gud in the same spirit, but with the goal of covering more advanced topics, the kinds of things that can really only be done from the command line because they're so complicated. Sometimes, you don't want a pretty interface, you want the commands to run quickly, and you want access to every command and all of its functionality. In Git Gud, we're going to deal with merge conflicts, multiple remotes, merges gone wrong, rebases gone horribly wrong and attempts to fix it that went even worse. We're going to show you how to set your remote to a tag and check out a branch in the process. Ever heard of [plumbing](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain)? We're going to learn about it. We're going to break it. We're going to be confused the whole time. Put short: We're going to Git Dirty. That's what makes us different.

In the meantime, comment here if you plan on working on a level or a set of levels and I'll mark it down here as we go through and implement them all.

#### Introduction
- [x] Introduction to Git Commits
- [x] Branching in Git
- [x] Merging in Git
- [x] Rebase Introduction

#### Ramping Up
- [x] Detached HEAD
- [x] Introduce ^
- [x] Introduce ~
- [x] Relative Refs 2
- [x] Reversing Changes

#### Moving Work Around
- [x] Cherry-picking Intro
- [x] Interactive Rebase Intro

#### A Mixed Bag
- [x] Grabbing just 1 commit
- [ ] Juggling Commits
- [ ] Juggling Commits 2
- [ ] Tags
- [ ] Describe

#### Advanced Topics
- [ ] Rebasing over 9000 times
- [ ] Multiple Parents
- [ ] Branch Spaghetti

#### Push and Pull
- [ ] Clone intro
- [ ] Remote Branches
- [ ] Fetchin'
- [ ] Pullin'
- [ ] Faking Teamwork
- [ ] Pushin'
- [ ] Diverged History

#### Advanced Remotes
- [ ] Push Master
- [ ] Merging with Remotes
- [ ] Remote tracking
- [ ] Git Push Arguments
- [ ] More Push Arguments
- [ ] Fetch Arguments
- [ ] Source of Nothing
- [ ] Pull Arguments

**Comment by bthayer2365** [comment]
#24 is currently working on Ramping Up

**Comment by TSSlade** [comment]
I'm happy to work on the `Push and Pull` `Clone Intro` and `Remote Branches` and stuff. Honestly just a little unclear about how to go ahead and contribute to that. Trying to figure out by analogy to what I already see in levels/intro.

To verify, it'd be something like:

1) Create a new folder set under `levels/` - presumably `levels/remotes` ?
2) Create `remotes/__init__.py` which imports the contents of (e.g.) `remotes/_cloneIntro`.
3) Populate `_cloneIntro` with `instructions.txt`, `setup.spec`, and `test.spec``
4) Populate `instructions.txt` the same challenge as the Learn Git Branching folks have set up.
...and then once I've figured out how the .spec class works, populate accordingly?

**Comment by bthayer2365** [comment]
Hey @TSSlade 
Yes, yes, yes and yes

Only comment is to name the levels with a lowercase. Some challenges (not necessarily this one) will include python files in the challenge direcotry, and for python modules, it's standard to use lowecase names with no spaces, so `remotes/_cloneIntro` would be `remotes/_cloneintro`

If you have any problems, just submit a pull request with what what have so far and then I can look at your code and help you out

**Comment by bthayer2365** [comment]
Just to be clear, when working on those challenges, you'll also be working on #51

**Comment by bthayer2365** [comment]
#24 has now been split into #66, #67, #68, and #69

**Comment by benthayer** [comment]
We're at the point now where it makes sense for all new levels to be created specifically for Git Gud.
