### ISSUE TITLE
Hooks being ignored due to them not being marked as executable

### ISSUE THREAD

**Issue by sahansk2** [benthayer/git-gud#77]
**Describe the bug**
Git hooks do not run when their corresponding git commands are executed in a git-gud directory.

**To Reproduce**
Run `git commit --amend` in an initialized git-gud directory to test the `post-rewrite` hook.

I have run `git gud start` in multiple fresh directories to see if it was a problem with directories already initialized and manipulated with other git commands, but it appears in the fresh directories as well.

**Expected behavior**
The git hooks should run without any problem, and without the user running the suggested command from git to ignore the corresponding warning.

**Screenshots/Output**
`$ git commit --amend`
```
hint: The '.git/hooks/post-rewrite' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[master 194c4cd] first commit
 Author: Git Gud <git-gud@example.com>
 Date: Sat Oct 26 21:20:50 2019 -0500
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1
```
**Environment**
OS: Ubuntu 18.04.3 LTS, 64-bit
python Version: 3.6.8
git Version: 2.17.1

**Comment by divCurlF** [comment]
Fixed in #79
