### ISSUE TITLE
Bug when opening contributors page in Firefox on Ubuntu

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#81]
See #75

**Comment by sahansk2** [comment]
As of 02/20/2020, I'm unable to replicate the bug.

Firefox Version: 73.0
Operating System: Ubuntu 18.04.4 LTS, x64 
git Version: 2.17.1

@Ishan1742 , are you still getting errors with trying to open `git gud contributors` when Firefox isn't open yet?

**Comment by Ishan1742** [comment]
I am currently on Manjaro 19.0.0

I don't have the bug here.
