### ISSUE TITLE
Instead of just instructions, also show a simulation

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#83]
Sometimes words can get to be too much, so I think watching the commands in action might be the most helpful way to learn. Alternate between running a command, then showing the tree, possibly with brief explanations. It might be worth it to do this as part of the instructions or maybe as something different.

**Comment by sahansk2** [comment]
I think it's worth mentioning that `asciinema` can record sessions and play them back right in the terminal, so if we want to, we can have a bunch of mini `asciinema` recordings and have them each play only after the user presses enter and reads the associated instructions.

However, making edits to instructions in the future becomes more difficult (though, that's not surprising).

**Comment by benthayer** [comment]
If you have an idea for how to implement this and want to try it out, go ahead. I wasn't sure how I'd want it done when I wrote this, so if you implement asciinema and it seems to flow well, we can talk about merging it!

**Comment by benthayer** [comment]
I think this will be solved by running the `git gud status`, `git gud show solution` (#154) and various other commands combined with a new paradigm of making shorter levels when necessary.

**Comment by benthayer** [comment]
Not to mention that we also have the asciinema in the readme
