### ISSUE TITLE
Track commits

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#87]
Must have
 -  [x] Make CSV file/track commits #40
 -  [x] Track rebases #43
 -  [ ] Track reverts #100
 -  [x] Add reverting notation to spec files #91

Obselete:
 -  [ ] Tag commits #34
 -  [ ] Tag merges #38
 -  [ ] Track merges #41

I'm still debating on the tagging since `git gud show-tree` already shows the names. If we update the tags, things would get visually crowded and it would be harder to read. It might be better to have users get used to checking out commit hashes and if there's ever a time when we need to access an otherwise unreferenced commit, then tag it manually or make a branch.

**Comment by bthayer2365** [comment]
@parkmichael777 Do you think you could lead the charge on these too?

**Comment by parkmichael777** [comment]
Sure, but probably later in the week/a week from now

**Comment by bthayer2365** [comment]
No problem, there's plenty of time

**Comment by benthayer** [comment]
@parkmichael777 Just a reminder that you can start working on these while #104 is in progress.

**Comment by benthayer** [comment]
Everything here is either done, changed or we won't do it. Closing
