### ISSUE TITLE
levels/challenges commands don't work outside of git gud repo

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#88]
These commands should be able to work wherever. If we're not in a git gud repo, it doesn't have access to a file operator, so it crashes when trying to output the current level. We should just skip that part if it fails. 

Challenges should require a level to be specified if we're not currently in a level.

Also, we should specify the full challenge name in both cases if we are in a git gud repo

**Comment by sahansk2** [comment]
Has this been resolved? When I try to run these commands on my Ubuntu machine outside of a git repo, `git gud levels` and `git gud skills` work fine.

**Comment by benthayer** [comment]
Yes, this was a while ago. Thanks for catching this.
